spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/corsidb
    username: courses
    password: courses
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8080

